joy:
  axis_linear:
    x: 3
    y: 2
    z: 1
  
  axis_angular:
    yaw: 0

  scale_attitude:
    x: 0.55
    y: 0.55
    z: 75
    yaw: 0.02
  
  scale_position:
    x: 0.05
    y: 0.05
    z: 0.05
    
  detection_state: 5
  left_seq: 2
  right_seq: 7
