control:

  hover: 0.5
  rate: 50

  ff_gain:
    velocity:
      x: 0.0
      y: 0.0
      z: 0.0
    acceleration:
      x: 0.0
      y: 0.0
      z: 0.0

  pos_x:
    kp: 1.25
    ki: 0.05
    kd: 0.0
    lim_low: -5
    lim_high: 5

  vel_x:
    kp: 0.2
    ki: 0.01
    kd: 0.0
    lim_low: -0.4
    lim_high: 0.4  

  pos_y:
    kp: 1.25
    ki: 0.05
    kd: 0.0
    lim_low: -5
    lim_high: 5

  vel_y:
    kp: 0.2
    ki: 0.01
    kd: 0.0
    lim_low: -0.4
    lim_high: 0.4 

  pos_z:
    kp: 2.2
    ki: 0.05
    kd: 0.0
    lim_low: -2.0
    lim_high: 3.0

  vel_z:
    kp: 0.2
    ki: 0.0
    kd: 0.0
    lim_low: -0.5
    lim_high: 0.5
  
  yaw_rate:
    kp: 1.25
    ki: 0.0
    kd: 0.0
    lim_low: -20
    lim_high: 20
